name: CI Workflow

on:
  pull_request:

env:
  GITHUB_ACTIONS: "true"

jobs:
  github-task-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show actor (user who triggered workflow)
        run: echo "Workflow triggered by ${{ github.actor }}"

      - name: Show GITHUB_ACTIONS variable
        run: echo "GITHUB_ACTIONS = $GITHUB_ACTIONS"

      - name: Show branch and repository
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.head_ref }}"

      - name: Show triggering event
        run: echo "Event:${{ github.event_name }}"
